config/routes.rb
Midas::Application.routes.draw do
  resources :users

  resources :sync_pages

  get "admin/index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :profile do
    get 'profile' => :index
  end

  get "reader/index"

  resources :books
  root :to => 'reader#index'

end

app/models/sync_page.rb
class SyncPage < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/sync_pages_controller.rb
class SyncPagesController < ApplicationController
  # GET /sync_pages
  # GET /sync_pages.json
  before_filter :authorize
  def index
    @sync_pages = SyncPage.all
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sync_pages }
    end
  end

  # GET /sync_pages/1
  # GET /sync_pages/1.json
  def show
    @sync_page = SyncPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sync_page }
    end
  end

  # GET /sync_pages/new
  # GET /sync_pages/new.json
  def new
    @sync_page = SyncPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sync_page }
    end
  end

  # GET /sync_pages/1/edit
  def edit
    @sync_page = SyncPage.find(params[:id])
  end

  # POST /sync_pages
  # POST /sync_pages.json
  def create
    @sync_page = SyncPage.new(params[:sync_page])
    @page = 2
    @user = User.find(session[:user_id])
    if (params[:current_page])
      @page = params[:current_page]
      @user.current_page = @page
    end

    respond_to do |format|
      if @sync_page.save
        format.html { redirect_to @sync_page, notice: 'Sync page was successfully created.' }
        format.json { render json: @sync_page, status: :created, location: @sync_page }
      else
        format.html { render action: "new" }
        format.json { render json: @sync_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sync_pages/1
  # PUT /sync_pages/1.json
  def update
    @sync_page = SyncPage.find(params[:id])

    respond_to do |format|
      if @sync_page.update_attributes(params[:sync_page])
        format.html { redirect_to @sync_page, notice: 'Sync page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sync_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sync_pages/1
  # DELETE /sync_pages/1.json
  def destroy
    @sync_page = SyncPage.find(params[:id])
    @sync_page.destroy

    respond_to do |format|
      format.html { redirect_to sync_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sync_pages_helper.rb
module SyncPagesHelper
end

app/views/sync_pages/_form.html.erb
<%= form_for(@sync_page) do |f| %>
  <% if @sync_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sync_page.errors.count, "error") %> prohibited this sync_page from being saved:</h2>

      <ul>
      <% @sync_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sync_pages/edit.html.erb
<h1>Editing sync_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @sync_page %> |
<%= link_to 'Back', sync_pages_path %>

app/views/sync_pages/index.html.erb
<h1>Listing sync_pages</h1>
<h1>page_num: <%= @user.current_page %> </h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sync_pages.each do |sync_page| %>
  <tr>
    <td><%= link_to 'Show', sync_page %></td>
    <td><%= link_to 'Edit', edit_sync_page_path(sync_page) %></td>
    <td><%= link_to 'Destroy', sync_page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<button onclick="click()">Click</button>
<%= link_to 'New Sync page', new_sync_page_path %>

app/views/sync_pages/new.html.erb
<h1>New sync_page</h1>

<%= render 'form' %>

<%= link_to 'Back', sync_pages_path %>

app/views/sync_pages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sync_page_path(@sync_page) %> |
<%= link_to 'Back', sync_pages_path %>