config/routes.rb
Midas::Application.routes.draw do
  resources :users

  resources :sync_pages

  get "admin/index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :profile do
    get 'profile' => :index
  end

  get "reader/index"

  resources :books
  root :to => 'reader#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :book_name, :cover_path, :max_page_num, :txt_path
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show

    @book = Book.find(params[:id])
    @file = File.readlines(@book.txt_path)
    @user = User.find(session[:user_id])
    @url = request.raw_host_with_port();
    @url_without_port = request.host;
    #@start_page = params[:start_page]
    #@end_page = params[:end_page]

    if params[:page]
      @page = Integer(params[:page])
      if @page <= 0
        @page = 1
      elsif @page > @book.max_page_num
        @page = @book.max_page_num
      end
    else
      @page = 1
    end



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
  def return_page(page_num)
    @book = Book.find(params[:id])
    current_book = File.readlines(@book.txt_path)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :book_name %><br />
    <%= f.text_field :book_name %>
  </div>
  <div class="field">
    <%= f.label :cover_path %><br />
    <%= f.text_field :cover_path %>
  </div>
  <div class="field">
    <%= f.label :txt_path %><br />
    <%= f.text_field :txt_path %>
  </div>
  <div class="field">
    <%= f.label :max_page_num %><br />
    <%= f.number_field :max_page_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Book name</th>
    <th>Cover path</th>
    <th>Txt path</th>
    <th>Max page num</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.author %></td>
    <td><%= book.book_name %></td>
    <td><%= image_tag(book.cover_path)%></td>
    <td><%= book.txt_path %></td>
    <td><%= book.max_page_num %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
    <%= javascript_include_tag "http://" + @url_without_port + ":9292/faye.js" %>
<script type="text/javascript"> 

    var page_num = <%= @page %>;
    var book_id= <%= @book.id %>;
    var prev_page = <%= @page-1 %>;
    var next_page = <%= @page+1 %>
    var max_page_num  = <%= @book.max_page_num %>
    onloadEvent();

  var page_num = <%= @page %>;
  var book_id= <%= @book.id %>;
  var prev_page = <%= @page-1 %>;
  var next_page = <%= @page+1 %>
  var max_page_num  = <%= @book.max_page_num %>
  var client_url = "http://" + "<%= @url_without_port %>" + ":9292/faye";
  def();
  onloadEvent();

</script>
<script type="text/javascript">

    $(function() {
            // Create a new client to connect to Faye
            var client = new Faye.Client('http://localhost:9292/faye');

  $(function() {
    // Create a new client to connect to Faye
    var client = new Faye.Client(client_url);
 
    // Handle form submissions and post messages to faye
    $('#prev_page').click(function(){
      // Publish the message to the public channel
      client.publish('/messages/public', {
        username: '<%= @user.name  %>',
        msg: prev_page
      });
 
      // Clear the message box
      //console.log(123)
 
      // Don't actually submit the form, otherwise the page will refresh.
      return false;
    });


    // Handle form submissions and post messages to faye
    $('#next_page').click(function(){
      // Publish the message to the public channel
      client.publish('/messages/public', {
        username: '<%= @user.name  %>',
        msg: next_page
      });
 
      // Clear the message box
      //console.log(123)
 
      // Don't actually submit the form, otherwise the page will refresh.
      return false;
    });
  });
</script>
<script>
  $(function() {
    // Create a new client to connect to Faye
      var client = new Faye.Client(client_url);
      console.log(client_url);
 
    // Subscribe to the public channel
    var public_subscription = client.subscribe('/messages/public', function(data) {
      console.log(data.username + ": " + data.msg);
      window.location="http://<%=@url%>/books/<%=@book.id%>?page="+data.msg.toString();


            // Handle form submissions and post messages to faye
            $('#prev_page').click(function(){
                // Publish the message to the public channel
                client.publish('/messages/public', {
username: '<%= @user.name  %>',
msg: prev_page
});

                // Clear the message box
                console.log(123)

                // Don't actually submit the form, otherwise the page will refresh.
                return false;
                });
            });
        </script>
        <script>
            $(function() {
                // Create a new client to connect to Faye
                var client = new Faye.Client('http://localhost:9292/faye');

                // Subscribe to the public channel
                var public_subscription = client.subscribe('/messages/public', function(data) {
                    console.log(data.username + ": " + data.msg);
                    window.location="http://0.0.0.0:3000/books/<%=@book.id%>?page="+data.msg.toString();

                });

                //jump to new page
                // Handle form submission to publish messages.
            });
        </script>
        <!--logo part-->
        <div class="show_logo">
            <a href="/"><img src="/images/logo.png" title="MidaReader"/></a>
        </div>
        <!--left_button part-->
        <img src="/images/comment_close.png" id="grey_tag" />
        <img src="/images/comment_open.png" id="red_tag"/>

        <!--Show text part-->
        <% if @book %>
            <div id="container">
                <div class="title_line">
                    <img src="/images/title_line.png"/>
                </div>
                <div class="page"> 
                    <div class="content" id="contentId">
                        <% for i in ((@page-1)*20)..(@page*20) %>
                            <p> <%= @file[i] %> </p>
                        <% end %>
                    </div>
                    <hr/><hr/>
                <% else %>
                    <div class="content">Please refresh.</div>
                <% end %>
            </div>
        </div>

        <!--page_button part-->
        <div class="page_button">
            <div>
                <a href = "<%=book_path(@book)%>?page=<%=@page+1%>" id="next_page" class="show_button"></br></br></br>next</a>
            </div>
            <div>
                <a href = "<%=book_path(@book)%>?page=<%=@page-1%>" id="prev_page" class="show_button"></br></br></br>prev</a>
            </div>
        </div>

        <img src="/images/pen.png" class="note" title="Take note"/>

        <!-- note part-->
        <div class="RTE" style="display:none">
            <div style="width:500px; text-align:left; margin-bottom:10px ">
                <input type="button" id="bold" style="height:21px; width:21px; font-weight:bold;" value="B" onClick="fontEdit('bold')" />
                <input type="button" id="italic" style="height:21px; width:21px; font-style:italic;" value="I" onClick="fontEdit('italic')" />
                <input type="button" id="underline" style="height:21px; width:21px; text-decoration:underline;" value="U" onClick="fontEdit('underline')" /> | 
                <input type="button" style="height:21px; width:21px;"value="L" onClick="fontEdit('justifyleft')" title="align left" />
                <input type="button" style="height:21px; width:21px;"value="C" onClick="fontEdit('justifycenter')" title="center" />
                <input type="button" style="height:21px; width:21px;"value="R" onClick="fontEdit('justifyright')" title="align right" /> | 
                <select id="fonts" onChange="fontEdit('fontname',this[this.selectedIndex].value)">
                    <option value="Arial">Arial</option>
                    <option value="Comic Sans MS">Comic Sans MS</option>
                    <option value="Courier New">Courier New</option>
                    <option value="Monotype Corsiva">Monotype</option>
                    <option value="Tahoma">Tahoma</option>
                    <option value="Times">Times</option>
                </select>
                <select id="size" onChange="fontEdit('fontsize',this[this.selectedIndex].value)">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <select id="color" onChange="fontEdit('ForeColor',this[this.selectedIndex].value)">
                    <option value="black">black</option>
                    <option style="color:red;" value="red">red</option>
                    <option style="color:blue;" value="blue">blue</option>
                    <option style="color:green;" value="green">green</option>
                    <option style="color:pink;" value="pink">pink</option>
                </select> | 
                <input type="button" style="height:21px; width:21px;"value="1" onClick="fontEdit('insertorderedlist')" title="Numbered List" />
                <input type="button" style="height:21px; width:21px;"value="?" onClick="fontEdit('insertunorderedlist')" title="Bullets List" />
                <input type="button" style="height:21px; width:21px;"value="?" onClick="fontEdit('outdent')" title="Outdent" />
                <input type="button" style="height:21px; width:21px;"value="?" onClick="fontEdit('indent')" title="Indent" />
            </div>
            <iframe id="textEditor" style="width:500px; height:170px;">
            </iframe>

        </div>