config/routes.rb
Midas::Application.routes.draw do
  resources :users

  resources :sync_pages

  get "admin/index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :profile do
    get 'profile' => :index
  end

  get "reader/index"

  resources :books
  root :to => 'reader#index'

end

app/controllers/reader_controller.rb
class ReaderController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/reader_helper.rb
module ReaderHelper
end

app/views/reader/index.html.erb
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Midas Reader</title>
        <script type="text/javascript" src="/static/js/jquery.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/css/index.css" />
    </head>
    <body>
        <div class="left_part">
            <!--Activity part-->
            <div class="activity">
                <img src="/images/index/book_tag2.png" class="tag2" />
                <div class="act_block">
                    <a href="/index"><img src="/images/index/activity1.png" width="300" height="200" class="act1"></a>
                    <a href="/index"><img src="/images/index/activity2.png" width="300" height="200" class="act2"></a>
                </div>
                <div class="act_logo"> 
                    <img src="/images/index/activity_logo.png" class="act_logo1"/>
                    <img src="/images/index/activity_logo.png" class="act_logo2"/>
                </div>
            </div>

            <img src="/images/index/separate.png" width="600"class="separation"/>
            <div class="book_list">
                <% if @books %>
                    <article> <% for book in @books %></article>
                        <a href="/books/<%=book.id%>" class="book"><img src="<%=book.cover_path%>" alt="Cover of <%= book.book_name %>" width="180" height="280"/></a>
                    <% end %>
                <% else %>
                    <article>Error, plz refresh.</article>
                <% end %>
            </div>
        </div>

        <div class="right_part"> 
            <img src="/images/index/logo.png" class="logo" height="50"/>
            <div class="user">
                <nav class="user_name">
                    <% if session[:user_id] %>
                <a href="/profile">
                   <img src="/images/index/user.png" class="user_image"/>
                </a>
                <div><a href="/profile" class="button">个人资料</a></div>
                        <%= button_to 'Logout', logout_path, :method => :delete, :class => "button" %>
                        <!-- user to be implemented -->
                    <% else %>
                        <a href="/login" class="button">登录</a>
                        <a href="/users/new" class="button">注册</a>
                    <% end %>
                </nav>
            </div>
            <div class="search">
                <input type="text" class="input" placeholder="To search"/>
                <input type="image" src="/images/index/search_button.png" class="search_button"/>
            </div> 
        </div>

    </body>
</html>